[package]
name = "rust_scrape"
version = "0.1.0"
authors = ["hunt3rkillerz"]
edition = "2018"


[dependencies]
select = "0.4.3"
rayon = "1.3.0"
rand = "0.7.3"
clap = "3.0.0-beta.1"
csv = "1.1"
reqwest = {version = "0.10.4", features = ["blocking"]}

